server_flask/models/Comment.py
from datetime import datetime
from sqlalchemy import Column, Integer, String, ForeignKey, DateTime
from sqlalchemy.orm import relationship
from server_flask.db import db

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey(
        'users.id', name='fk_comment_users_id', ondelete="CASCADE"), nullable=True)
    post_id = db.Column(db.Integer, db.ForeignKey(
        'posts.id', name='fk_comment_posts_id',  ondelete="CASCADE"), nullable=True)
    orders_id = db.Column(db.Integer, db.ForeignKey(
        'orders.id', name='fk_comment_orders_id', ondelete="CASCADE"), nullable=True)
    replies = db.relationship('Reply', back_populates='comment')
    likes = db.relationship('Likes', backref='comment', passive_deletes=True)

server_flask/routes/Blog.py
from flask import Blueprint, redirect, render_template, request, flash, redirect, url_for, jsonify, session
from server_flask.models import Comment, Posts, Reply, Reply2, Users
from flask_login import login_required, current_user
from server_flask.db import db
import sys

# from app.utils.auth import login_required

bp = Blueprint('Blog', __name__, template_folder='templates')



@bp.route('/blog', methods=['POST', 'GET'])
@login_required
def Blog():
    if request.method == 'POST':
        task_content = request.form['content']
        task_name_post = request.form['name_post']
        new_task = Posts(text=task_content, name_post=task_name_post)
        #        try:
        db.session.add(new_task)
        db.session.commit()
        print(">>> Add datebase")
        return redirect('/blog')
    else:
        tasks_posts = Posts.query.order_by(Posts.timestamp).all()
        tasks_users = Users.query.order_by(Users.timestamp).all()
        return render_template('blog.html', tasks_users=tasks_users, posts=tasks_posts,  user=current_user)

@bp.route('/blog/delete/<int:id>')
@login_required
def delete(id):
    task_to_delete = Posts.query.get_or_404(id)
    try:
        print(">>> Start delete in datebase")
        db.session.delete(task_to_delete)
        db.session.commit()
        print(">>> Delete in datebase")
        return redirect('/blog')
    except:
        return 'There was an issue deleting that task'

@bp.route('/blog/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id):
    task_update = Posts.query.get_or_404(id)

    if request.method == 'POST':
        task_update.text = request.form['content']
        try:
            db.session.commit()
            print(">>> Update in datebase")
            return redirect('/blog')
        except:
            return 'There was an issue updating your task'
    else:
        return render_template('blog_update.html', task=task_update)

@bp.route('/blog/add_post', methods=['POST', 'GET'])
@login_required
def add_post():
    if request.method == 'POST':
        task_name_post = request.form['name_post']
        task_content = request.form['content']
        author_id = current_user
        if not task_content:
            flash('Post cannot be empty', category='error')
        else:
            post = Posts(name_post=task_name_post, text=task_content, author_id=author_id.id)
            db.session.add(post)
            db.session.commit()
            flash('Post created!', category='success')
            return redirect(url_for('Blog.Blog'))

    return render_template('add_post.html', user=current_user)

server_flask/routes/Comment.py
from flask import Blueprint, redirect, render_template, request, jsonify, session, flash
from server_flask.models import Comment, Posts, Reply, Reply2, Users
from server_flask.db import db
import sys

bp = Blueprint('comment', __name__, template_folder='templates')

@bp.route("/comments", methods=['POST', 'GET'])
def comments():
    if request.method == 'POST':
        text = request.form['comment']
        if not text:
            flash('Post cannot be empty', category='error')
        else:
            new_task = Comment(text=text)
            db.session.add(new_task)
            db.session.commit()
            print(">>> Add datebase")
            return redirect('/comments')
    else:
        comments = Comment.query.order_by(Comment.timestamp).all()
        reply = Reply.query.order_by(Reply.timestamp).all()
        return render_template('comments.html', comments=comments, reply=reply)

@bp.route('/add_reply/<int:parent_id>', methods=['GET', 'POST'])
def add_reply(parent_id):
    # Обработка формы для ответа на комментарий с ID comment_id
    if request.method == 'POST':
        reply_text = request.form.get('reply_text')
        # Добавьте код для сохранения ответа и комментария в базу данных
        new_task = Reply(text=reply_text, comment_id=parent_id)

#        try:
        db.session.add(new_task)
        db.session.commit()
        print(">>> Add datebase")
        return redirect('/comments')
    return render_template('add_reply.html', parent_id=parent_id)

@bp.route('/add_reply2/<int:parent_id>', methods=['GET', 'POST'])
def add_reply2(parent_id):
    # Обработка формы для ответа на комментарий с ID comment_id
    if request.method == 'POST':
        reply_text = request.form.get('reply_text')
        # Добавьте код для сохранения ответа и комментария в базу данных
        new_task = Reply2(text=reply_text, comment_id=parent_id)

#        try:
        with app.app_context():
            db.session.add(new_task)
            db.session.commit()
            print(">>> Add datebase 2")
            return redirect('/comments')
    return render_template('add_reply2.html', parent_id=parent_id)

@bp.route('/delete/<int:id>')
def delete(id):
    task_to_delete = Comment.query.get_or_404(id)
    try:
        print(">>> Start delete in datebase")
        db.session.delete(task_to_delete)
        db.session.commit()
        print(">>> Delete in datebase")
        return redirect('/')
    except:
        return 'There was an issue deleting that task'

server_flask/templates/add_post.html
{% extends 'layout/base.html' %}

{% block head %}

{% endblock %}

{% block body %}
	<div class="content">
		<h1 style="text-align: center;">
			Додайте статю
		</h1>


		<form action="{{ url_for('Blog.add_post') }}" method="post">
			 <textarea class="form-control bg-light" name="name_post" rows="1" cols="50" placeholder="Введите название"></textarea><br>
			<textarea class="form-control bg-light" name="content" rows="4" cols="50" placeholder="Введите ваш текст"></textarea><br>
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Зберегти пост</button>
		</form>

	</div>

{% endblock %}

server_flask/templates/add_reply.html
{% extends 'layout/base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="content">
	 <h1>Ответ на комментарий</h1>
	 <form action="{{ url_for('comment.add_reply', parent_id=parent_id) }}" method="post">
        <textarea name="reply_text" rows="4" cols="50" placeholder="Введите ваш ответ"></textarea><br>
        <button type="submit">Отправить ответ</button>
    </form>
</div>
{% endblock %}

server_flask/templates/add_reply2.html
{% extends 'layout/base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="content">
	 <h1>Ответ на комментарий</h1>
	 <form action="{{ url_for('add_reply2', parent_id=parent_id) }}" method="post">
        <textarea name="reply_text" rows="4" cols="50" placeholder="Введите ваш ответ"></textarea><br>
        <button type="submit">Отправить ответ</button>
    </form>
</div>
{% endblock %}

server_flask/templates/blog.html
{% extends 'layout/base.html' %} {% block title %}Home{% endblock %}

{% block body %}

<h1 align="center">{% block header %}Posts{% endblock %}</h1>
<div id="posts">
  {% for post in posts %}
  <div class="content">
    <div class="card-header d-flex justify-content-between align-items-center">
      <a href="/blog/{{user.username}}">{{user.username}}</a>
<!--      <div>-->
<!--        <span id="likes-count-{{post.id}}">-->
<!--        {{ post.likes|length }}</span>-->
<!--        {% if user.id in post.likes|map(attribute="author")|list %}-->
<!--        <i-->
<!--          class="fas fa-thumbs-up"-->
<!--          id="like-button-{{post.id}}"-->
<!--          onclick="like({{post.id}})"-->
<!--        ></i>-->
<!--        {% else %}-->
<!--        <i-->
<!--          class="far fa-thumbs-up"-->
<!--          id="like-button-{{post.id}}"-->
<!--          onclick="like({{post.id}})"-->
<!--        ></i>-->
<!--        {% endif %} {% if user.id == post.author %}-->
<!--        <div class="btn-group">-->
<!--          <button-->
<!--            type="button"-->
<!--            class="btn btn-sm btn-primary dropdown-toggle"-->
<!--            data-bs-toggle="dropdown"-->
<!--          ></button>-->
<!--          <ul class="dropdown-menu">-->
<!--            <li>-->
<!--              <a href="/delete-post/{{post.id}}" class="dropdown-item"-->
<!--                >Delete</a-->
<!--              >-->
<!--            </li>-->
<!--          </ul>-->
<!--        </div>-->
<!--        {% endif %}-->
<!--      </div>-->
    </div>
    <div class="card-body">
      <div class="card-text"> <a href="/blog/{{user.username}}/{{post.id}}">{{post.name_post}}</a></div>
      <br />
      <div class="collapse" id="comments-{{post.id}}">
        <div class="card">
          <div class="card-body" id="comments-expanded-{{post.id}}">
            {% for comment in post.comments %}
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <a href="/posts/{{comment.user.username}}"
                  >{{comment.user.username}}</a
                >: {{comment.text}}
              </div>
              <div>
                <small class="text-muted"> {{comment.date_created}}</small>
                {% if user.id == comment.author or user.id == post.author %}
                <div class="btn-group">
                  <button
                    type="button"
                    class="btn btn-sm btn-primary dropdown-toggle"
                    data-bs-toggle="dropdown"
                  ></button>
                  <ul class="dropdown-menu">
                    <li>
                      <a
                        href="/delete-comment/{{comment.id}}"
                        class="dropdown-item"
                        >Delete</a
                      >
                    </li>
                  </ul>
                </div>
                {% endif %}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <p class="card-text">
        {% if post.comments|length > 0 %}
        <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
          <small>View {{post.comments|length}} Comments</small>
        </a>
        {% else %}
        <small class="text-muted">No Comments</small>
        {% endif %}
      </p>
      <form
        class="input-group mb-3"
        method="POST"
        action="/create-comment/{{post.id}}"
      >
        <input
          type="text"
          id="text"
          name="text"
          class="form-control"
          placeholder="Comment something!"
        />
        <button type="submit" class="btn btn-primary">Comment</button>
      </form>
    </div>
    <div class="card-footer text-muted">{{post.date_created}}</div>
  </div>
  <br/ > {% endfor %}
</div>

{% block footer %}
<div align="center">
  <a href="blog/add_post"
    ><button type="button" class="btn btn-primary btn-lg">
      Create a Post
    </button></a
  >
   <br/ >
   <br/ >
</div>
{% endblock %} {% endblock %}

server_flask/templates/blog_update.html
{% extends 'layout/base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="content">
	<h1 style="text-align: center;">
		Update Blog
	</h1>

	<form action="/blog/update/{{task.id}}" method="POST">
		<textarea type="text" name="content" rows="4" cols="50" id="content" >{{task.text}}</textarea><br>
		<button class="btn btn-outline-success btn-lg" type="submit" >Обновить пост</button>
	</form>

</div>
{% endblock %}

server_flask/templates/comments.html
{% extends 'layout/base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="content">

  <h1>Система Комментариев с Ответами</h1>

    <form action="{{ url_for('comment.comments') }}" method="post">
        <textarea class="bg-light" name="comment" rows="4" cols="50" placeholder="Введите ваш комментарий"></textarea><br>
        <button class="btn btn-outline-success btn-lg my-sm-0" type="submit">Отправить комментарий</button>
    </form>

	{% if comments|length < 1 %}
	<h4 style="text-align: center;">There are no comment. Create one below!</h4>
	{% else %}



  
    

    <h2>Комментарии:</h2>
     <ul class="bg-light">
        {% for comment in comments %}
            <li class="bg-light">
                {{ comment.text }}

                <a class="btn btn-outline-success my-sm-0" style="margin-left:20px;"  href="{{ url_for('comment.add_reply', parent_id=comment.id) }}" >Ответить</a>

                <ul>
                    {% for reply in comment.replies %}
                        <li>
                          {{ reply.text }}
                           <a class="btn btn-outline-success my-sm-0" style="margin-left:20px;" href="{{ url_for('comment.add_reply2', parent_id=reply.id) }}">Ответить</a>
                            <ul>
                        {% for reply2 in reply.replies %}
                          <li>
                            {{ reply2.text }}
                            
                          </li>
                        {% endfor %}
                             </ul>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>

<!-- <div id="comments">
  {% for task in tasks %}
    <div class="comment">
      <p>{{ task.content }}</p>
      {% if "replies" in comment %}
        <div class="replies">
          {% for reply in comment.replies %}
            <div class="reply">
              <p>{{ reply.comment }}</p>
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  {% endfor %}
</div> -->
	{% endif %}
<!-- 	<form action="/comments" method="POST">
		<input type="text" name="text" id="content">
		<input type="submit" value="ADD COMMENT">
	</form> -->

</div>
{% endblock %}

server_flask/templates/index.html
{% extends 'layout/base.html' %}

{% block head %}
<style>
    /* body, html {
        margin: 10 10 10 10;
        padding: 0;
        height: 90%;
    } */
    /* .fullscreen-image {
        position: fixed;
        top: 10;
        left: 0;
        width: 100%;
        height: 100%;
        background-image: url('{{url_for('static', filename='images/cool-background(1).png')}}');
        background-size: cover;
        background-position: center;
    } 
	*/
	html,
body {
  margin: 10, 10, 10, 10;
  padding: 10;
  background-color: #f8f9fa;
}

.background {
  position: absolute;
  display: block; 
  top: 10;
  left: 0;
  z-index: 0;
  
}
</style>
{% endblock %}

{% block body %}
<canvas class="background"></canvas>
<script src="https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.2.3/particles.min.js"></script>
<script>window.onload = function() {
	Particles.init({
  // normal options
  selector: '.background',
  maxParticles: 50,
  connectParticles: true,
  sizeVariations: 10,
  speed: 0.4,
  minDistance: 150,
  color: "#17a2b8"
  // options for breakpoints
//   responsive: [
//     {
//       breakpoint: 1,
//       options: {
//         maxParticles: 200,
//         color: '#48F2E3',
//         connectParticles: true
//       }
//     }, {
//       breakpoint: 4,
//       options: {
//         maxParticles: 100,
//         connectParticles: true
//       }
//     }, {
//       breakpoint: 5,
//       options: {
//         maxParticles: 0 // disables particles.js
//       }
//     }
//   ]
});
  };</script>
<!-- <div class="fullscreen-image"></div> -->
	<!-- {% if tasks|length < 1 %}
	<h4 style="text-align: center;">There are no comment. Create one below!</h4>
	{% else %}
	<table>
		<tr>
			<th>Login</th>
			<th>Comment</th>
			<th>Added</th>
			<th>Actions</th>
		</tr>
		{% for task in tasks %}
			<tr>
				<td>{{task.text}}</td>
				<td>{{task.timestamp}}</td>	
				
				
				<td>
					<a href="/delete/{{task.id}}">Delete</a>
					<br>
					<a href="/update/{{task.id}}">Update</a>
				</td>

			</tr>
		{% endfor %}
	</table>
	{% endif %}
	<form action="/" method="POST">
		<input type="text" name="conect" id="conect" value="Login">
		<input type="text" name="content" id="content">
		<input type="submit" value="ADD COMMENT">
	</form>

</div> -->
{% endblock %}

server_flask/templates/login.html
{% extends 'layout/base.html' %}
{% block title %}Login{% endblock %}
{% block head %}

{% endblock %}

{% block body %}
    <div class="content">
        <form method="POST">
          <h3 align="center">Login</h3>
          <div class="form-group">
            <label for="email">Email Address</label>
            <input
              type="text"
              id="email"
              name="email"
              class="form-control"
              placeholder="Enter Email"
            />
            <label for="password">Password</label>
            <input
              type="password"
              id="password"
              name="password"
              class="form-control"
              placeholder="Enter Password"
            />
            <br />
            <div align="center">
              <button class="btn btn-primary" type="submit">Login</button>
            </div>
          </div>
        </form>
    </div>
{% endblock %}

server_flask/templates/signup.html
{% extends 'layout/base.html' %}
{% block title %}Sing Up{% endblock %}
{% block head %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

{% block body %}
    <div class="content">
        <form method="POST">
          <h3 align="center">Реєстрація</h3>
        </br>
            <div class="form-group">
            <div class="row d-flex justify-content-center">
                <label for="username">Нікнейм</label>
                    <input
                      type="text"
                      id="username"
                      name="username"
                      class="form-control"
                      placeholder="Введіть Нікнейм"
                    />
            </div>
            <div class="row d-flex justify-content-center">
                <label for="email">Email</label>
                    <input
                      type="text"
                      id="email"
                      name="email"
                      class="form-control"
                      placeholder="Введіть Email"
                    />
            </div>
            <div class="row d-flex justify-content-center">
                <label for="password1">Пароль</label>
                    <input
                      type="password"
                      id="password1"
                      name="password1"
                      class="form-control"
                      placeholder="Введіть пароль"
                    />
            </div>
            <div class="row d-flex justify-content-center">
                <label for="password2">Повторіть пароль</label>
                    <input
                      type="password"
                      id="password2"
                      name="password2"
                      class="form-control"
                      placeholder="Введіть пароль знову"
                    />
            </div>
            </br>
            <div class="row d-flex justify-content-center">
                        <div class="g-recaptcha" data-sitekey="6LfN0-8oAAAAALd7VinSJSrw7rEqvGaSdIFSwux1"></div>                     
            </div>               
            </br>
            <div class="row d-flex justify-content-center">
                     <button class="btn btn-primary" type="submit">Зареєструватися</button>
            </div>
            
            </div>
        </form>
    </div>
{% endblock %}

server_flask/templates/update.html
{% extends 'layout/base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div class="content">
	<h1 style="text-align: center;">
		Update Comment
	</h1>

	<form action="/update/{{task.id}}" method="POST">
		<input type="text" name="content" id="content" value="{{task.text}}">
		<input type="submit" value="Update">
	</form>

</div>
{% endblock %}